using System.Text.Json.Nodes;
namespace Construct.Companion.Core.Remote;
public sealed partial class RemoteHostClient
{
    public Task<JsonNode?> WhoamiAsync(CancellationToken cancellationToken = default) => RequestAsync("GET", "/whoami", null, cancellationToken);
    public Task<JsonNode?> ListVmsAsync(CancellationToken cancellationToken = default) => RequestAsync("GET", "/vms", null, cancellationToken);
    public Task<JsonNode?> GetVmAsync(string name, CancellationToken cancellationToken = default) => RequestAsync("GET", $"/vms/{RemoteHost.Encode(name)}", null, cancellationToken);
    public Task<JsonNode?> GetStateAsync(string name, CancellationToken cancellationToken = default) => RequestAsync("GET", $"/vms/{RemoteHost.Encode(name)}/state", null, cancellationToken);
    public Task<JsonNode?> PowerAsync(string name, string action, CancellationToken cancellationToken = default) => RequestAsync("POST", $"/vms/{RemoteHost.Encode(name)}/power", new JsonObject { ["action"] = action }, cancellationToken);
    public Task<JsonNode?> CreateVmAsync(JsonNode? spec, CancellationToken cancellationToken = default) => RequestAsync("POST", "/vms", spec, cancellationToken);
    public Task<JsonNode?> DeleteVmAsync(string name, JsonNode? body, CancellationToken cancellationToken = default) => RequestAsync("DELETE", $"/vms/{RemoteHost.Encode(name)}", body, cancellationToken);
    public Task<JsonNode?> GetJobAsync(string id, CancellationToken cancellationToken = default) => RequestAsync("GET", $"/jobs/{RemoteHost.Encode(id)}", null, cancellationToken);
    public Task<JsonNode?> HealthAsync(CancellationToken cancellationToken = default) => RequestAsync("GET", "/health", null, cancellationToken);
    public Task<JsonNode?> HostCapabilitiesAsync(CancellationToken cancellationToken = default) => RequestAsync("GET", "/host/capabilities", null, cancellationToken);
    public Task<JsonNode?> VmIdentityAsync(string name, CancellationToken cancellationToken = default) => RequestAsync("GET", $"/vms/{RemoteHost.Encode(name)}/identity", null, cancellationToken);
    public Task<JsonNode?> VmCapabilitiesAsync(string name, CancellationToken cancellationToken = default) => RequestAsync("GET", $"/vms/{RemoteHost.Encode(name)}/capabilities", null, cancellationToken);
    public Task<JsonNode?> HostStatusAsync(CancellationToken cancellationToken = default) => RequestAsync("GET", "/host/status", null, cancellationToken);
    public Task<JsonNode?> HostCapacityAsync(bool refresh, CancellationToken cancellationToken = default) => RequestAsync("GET", "/host/capacity" + RemoteHost.BuildQuery(new JsonObject { ["refresh"] = refresh ? "true" : null }), null, cancellationToken);
    public Task<JsonNode?> HostConfigAsync(CancellationToken cancellationToken = default) => RequestAsync("GET", "/host/config", null, cancellationToken);
    public Task<JsonNode?> PutHostConfigAsync(JsonNode? body, CancellationToken cancellationToken = default) => RequestAsync("PUT", "/host/config", body, cancellationToken);
    public Task<JsonNode?> IsoCatalogAsync(CancellationToken cancellationToken = default) => RequestAsync("GET", "/host/iso-catalog", null, cancellationToken);
    public Task<JsonNode?> UsersAsync(CancellationToken cancellationToken = default) => RequestAsync("GET", "/users", null, cancellationToken);
    public Task<JsonNode?> GetUserAsync(string name, CancellationToken cancellationToken = default) => RequestAsync("GET", $"/users/{RemoteHost.Encode(name)}", null, cancellationToken);
    public Task<JsonNode?> CreateUserAsync(JsonNode? body, CancellationToken cancellationToken = default) => RequestAsync("POST", "/users", body, cancellationToken);
    public Task<JsonNode?> UpdateUserAsync(string name, JsonNode? body, CancellationToken cancellationToken = default) => RequestAsync("PUT", $"/users/{RemoteHost.Encode(name)}", body, cancellationToken);
    public Task<JsonNode?> DeleteUserAsync(string name, CancellationToken cancellationToken = default) => RequestAsync("DELETE", $"/users/{RemoteHost.Encode(name)}", null, cancellationToken);
    public Task<JsonNode?> UserAllowanceAsync(string name, CancellationToken cancellationToken = default) => RequestAsync("GET", $"/users/{RemoteHost.Encode(name)}/allowance", null, cancellationToken);
    public Task<JsonNode?> PutUserAllowanceAsync(string name, JsonNode? body, CancellationToken cancellationToken = default) => RequestAsync("PUT", $"/users/{RemoteHost.Encode(name)}/allowance", body, cancellationToken);
    public Task<JsonNode?> UserTokensAsync(string name, CancellationToken cancellationToken = default) => RequestAsync("GET", $"/users/{RemoteHost.Encode(name)}/tokens", null, cancellationToken);
    public Task<JsonNode?> IssueUserTokenAsync(string name, JsonNode? body, CancellationToken cancellationToken = default) => RequestAsync("POST", $"/users/{RemoteHost.Encode(name)}/tokens", body ?? new JsonObject(), cancellationToken);
    public Task<JsonNode?> RevokeUserTokenAsync(string name, string id, CancellationToken cancellationToken = default) => RequestAsync("DELETE", $"/users/{RemoteHost.Encode(name)}/tokens/{RemoteHost.Encode(id)}", null, cancellationToken);
    public Task<JsonNode?> VmsAsync(JsonObject? query, CancellationToken cancellationToken = default) => RequestAsync("GET", "/vms" + RemoteHost.BuildQuery(query), null, cancellationToken);
    public Task<JsonNode?> SharedVmsAsync(CancellationToken cancellationToken = default) => RequestAsync("GET", "/vms/shared", null, cancellationToken);
    public Task<JsonNode?> ChildrenAsync(string parent, CancellationToken cancellationToken = default) => RequestAsync("GET", $"/vms/{RemoteHost.Encode(parent)}/children", null, cancellationToken);
    public Task<JsonNode?> OverridesAsync(string name, CancellationToken cancellationToken = default) => RequestAsync("GET", $"/vms/{RemoteHost.Encode(name)}/overrides", null, cancellationToken);
    public Task<JsonNode?> PutOverridesAsync(string name, JsonNode? body, CancellationToken cancellationToken = default) => RequestAsync("PUT", $"/vms/{RemoteHost.Encode(name)}/overrides", body, cancellationToken);
    public Task<JsonNode?> DeleteOverridesAsync(string name, CancellationToken cancellationToken = default) => RequestAsync("DELETE", $"/vms/{RemoteHost.Encode(name)}/overrides", null, cancellationToken);
    public Task<JsonNode?> LifecycleAsync(string name, JsonNode? body, CancellationToken cancellationToken = default) => RequestAsync("POST", $"/vms/{RemoteHost.Encode(name)}/lifecycle", body, cancellationToken);
    public Task<JsonNode?> SetVmSharingAsync(string name, JsonNode? body, CancellationToken cancellationToken = default) => RequestAsync("PUT", $"/vms/{RemoteHost.Encode(name)}/sharing", body, cancellationToken);
    public Task<JsonNode?> RenewVmLeaseAsync(string name, JsonNode? body, CancellationToken cancellationToken = default) => RequestAsync("POST", $"/vms/{RemoteHost.Encode(name)}/lease", body, cancellationToken);
    public Task<JsonNode?> RotateVmTokenAsync(string name, JsonNode? body, CancellationToken cancellationToken = default) => RequestAsync("POST", $"/vms/{RemoteHost.Encode(name)}/token", body ?? new JsonObject(), cancellationToken);
    public Task<JsonNode?> RevokeVmTokenAsync(string name, CancellationToken cancellationToken = default) => RequestAsync("DELETE", $"/vms/{RemoteHost.Encode(name)}/token", null, cancellationToken);
    public Task<JsonNode?> MediaAsync(JsonObject? query, CancellationToken cancellationToken = default) => RequestAsync("GET", "/media" + RemoteHost.BuildQuery(query), null, cancellationToken);
    public Task<JsonNode?> MediaItemAsync(string id, CancellationToken cancellationToken = default) => RequestAsync("GET", $"/media/{RemoteHost.Encode(id)}", null, cancellationToken);
    public Task<JsonNode?> MediaReferencesAsync(string id, CancellationToken cancellationToken = default) => RequestAsync("GET", $"/media/{RemoteHost.Encode(id)}/references", null, cancellationToken);
    public Task<JsonNode?> DeleteMediaAsync(string id, CancellationToken cancellationToken = default) => RequestAsync("DELETE", $"/media/{RemoteHost.Encode(id)}", null, cancellationToken);
    public Task<JsonNode?> MediaCleanupAsync(CancellationToken cancellationToken = default) => RequestAsync("POST", "/media/cleanup", new JsonObject(), cancellationToken);
    public Task<JsonNode?> JobsAsync(JsonObject? query, CancellationToken cancellationToken = default) => RequestAsync("GET", "/jobs" + RemoteHost.BuildQuery(query), null, cancellationToken);
    public Task<JsonNode?> CancelJobAsync(string id, CancellationToken cancellationToken = default) => RequestAsync("POST", $"/jobs/{RemoteHost.Encode(id)}/cancel", new JsonObject(), cancellationToken);
    public Task<JsonNode?> AuditAsync(JsonObject? query, CancellationToken cancellationToken = default) => RequestAsync("GET", "/audit" + RemoteHost.BuildQuery(query), null, cancellationToken);
    public Task<JsonNode?> ForwardsViaAsync(string primary, CancellationToken cancellationToken = default) => RequestAsync("GET", $"/vms/{RemoteHost.Encode(primary)}/forwards" + RemoteHost.BuildQuery(new JsonObject { ["via"] = primary }), null, cancellationToken);
    public Task<JsonNode?> UpdatesStatusAsync(CancellationToken cancellationToken = default) => RequestAsync("GET", "/host/updates/status", null, cancellationToken);
    public Task<JsonNode?> UpdatesCheckAsync(JsonNode? body, CancellationToken cancellationToken = default) => RequestAsync("POST", "/host/updates/check", body ?? new JsonObject(), cancellationToken);
    public Task<JsonNode?> UpdatesStageAsync(JsonNode? body, CancellationToken cancellationToken = default) => RequestAsync("POST", "/host/updates/stage", body ?? new JsonObject(), cancellationToken);
    public Task<JsonNode?> UpdatesApplyAsync(JsonNode? body, CancellationToken cancellationToken = default) => RequestAsync("POST", "/host/updates/apply", body, cancellationToken);
    public Task<JsonNode?> UpdatesCancelAsync(JsonNode? body, CancellationToken cancellationToken = default) => RequestAsync("POST", "/host/updates/cancel", body, cancellationToken);
    public Task<JsonNode?> UpdatesResolveAsync(JsonNode? body, CancellationToken cancellationToken = default) => RequestAsync("POST", "/host/updates/resolve", body, cancellationToken);
    public async Task<JsonObject?> GetEndpointAsync(string name, CancellationToken cancellationToken = default) => RemoteHost.ReadEndpoint(await RequestAsync("GET", $"/vms/{RemoteHost.Encode(name)}/endpoint", cancellationToken: cancellationToken));
}
